Get http://localhost:6000/getBlog

### signup
POST http://localhost:5000/signup
Content-Type: application/json

{
    "email": "eric@gmail.com",
    "password": "eric247"
}

### signup
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "eric@gmail.com",
    "password": "eric247"
}

###
POST http://localhost:8000/postBlog
Content-Type: multipart/form-data

{
    "title": "My First Blog Post",
    "summary": "Testing if it works",
    "content": "This is my first blog post!",
    "author": "Eric",
    "image": "https://c.files.bbci.co.uk/10DD8/production/_114608096_wizkidsmileofficialvideo.jpg"
}